services:
  mysql:
    image: mysql:8.4
    container_name: blog111-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blog111
      MYSQL_USER: blog111
      MYSQL_PASSWORD: blog111
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
