FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace

COPY pom.xml .
COPY src ./src

RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /workspace/target/blog-api-0.0.1-SNAPSHOT.jar /app/blog-api.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/blog-api.jar"]
